# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.0'
end
